### import lip

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

### download data

In [ ]:
## download data
df = pd.read_csv('/content/car_evaluation2.csv', encoding='latin-1')
# or try 'ISO-8859-1', 'cp1252' if 'latin-1' doesn't work
df.head(3)

,buying,maint,doors,persons,lug_boot,safety,class,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,vhigh,vhigh,2,2,small,low,unacc,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,vhigh,vhigh,2,2,small,med,unacc,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,vhigh,vhigh,2,2,small,high,unacc,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1326 entries, 0 to 1325
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   buying       1326 non-null   object
 1   maint        1323 non-null   object
 2   doors        1322 non-null   object
 3   persons      1322 non-null   object
 4   lug_boot     1322 non-null   object
 5   safety       1321 non-null   object
 6   class        1320 non-null   object
 7   Unnamed: 7   1 non-null      object
 8   Unnamed: 8   1 non-null      object
 9   Unnamed: 9   1 non-null      object
 10  Unnamed: 10  1 non-null      object
 11  Unnamed: 11  1 non-null      object
 12  Unnamed: 12  1 non-null      object
 13  Unnamed: 13  1 non-null      object
dtypes: object(14)
memory usage: 145.2+ KB

In [ ]:
df = df[['buying','maint','doors','persons','lug_boot','safety','class']]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1326 entries, 0 to 1325
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1326 non-null   object
 1   maint     1323 non-null   object
 2   doors     1322 non-null   object
 3   persons   1322 non-null   object
 4   lug_boot  1322 non-null   object
 5   safety    1321 non-null   object
 6   class     1320 non-null   object
dtypes: object(7)
memory usage: 72.6+ KB

### drop na

In [ ]:
df.isna().sum()

buying      0
maint       3
doors       4
persons     4
lug_boot    4
safety      5
class       6
dtype: int64

In [ ]:
df.isnull().mean()*100

buying      0.000000
maint       0.226244
doors       0.301659
persons     0.301659
lug_boot    0.301659
safety      0.377074
class       0.452489
dtype: float64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isna().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [ ]:
value_to_drop = "Úí³bÛqo2+eÛPL IndexerVolumeGuid%p^$KÃ
ì³bF-J¡ì³bÛ-J¡ì³bÛæíÓ+eÛ
 WPSettings.datÿÿÿÿyGFFILE0ñD8@%F`HKÃ
ì³bÛ-J¡ì³bÛ-J¡ì³bÛæíÓ+eÛ 0x^$KÃ
ì³bÛKÃ
ì³bÛKÃ
ì³bÛKÃ
ì³bÛ WPSettings.dat(

¡÷mæúqÚúÿÿÿÿyGFFFILE0¶D8&E`HB"
df = df[df['class'] != value_to_drop]
print(df['class'].value_counts())

class
unacc    909
acc      276
good      69
vgood     65
Name: count, dtype: int64

/usr/local/lib/python3.11/dist-packages/IPython/core/inputtransformer2.py:478: UserWarning: `make_tokens_by_line` received a list of lines which do not have lineending markers ('\n', '\r', '\r\n', '\x0b', '\x0c'), behavior will be unspecified
  warnings.warn("`make_tokens_by_line` received a list of lines which do not have lineending markers ('\\n', '\\r', '\\r\\n', '\\x0b', '\\x0c'), behavior will be unspecified")

In [ ]:
df['class'].value_counts()

class
unacc    909
acc      276
good      69
vgood     65
Name: count, dtype: int64

### check duplicates

In [ ]:
df.duplicated().sum()

0

### descripe data

In [ ]:
df.describe()

       buying maint  doors persons lug_boot safety  class
count    1319  1319   1319    1319     1319   1319   1319
unique      4     4      4       3        3      3      4
top       med  high  5more       4    small    low  unacc
freq      432   432    343     441      441    440    909

In [ ]:
df.nunique()

buying      4
maint       4
doors       4
persons     3
lug_boot    3
safety      3
class       4
dtype: int64

### encoding data

In [ ]:
print(df.info())
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical Columns:", categorical_columns)

<class 'pandas.core.frame.DataFrame'>
Index: 1319 entries, 0 to 1325
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1319 non-null   object
 1   maint     1319 non-null   object
 2   doors     1319 non-null   object
 3   persons   1319 non-null   object
 4   lug_boot  1319 non-null   object
 5   safety    1319 non-null   object
 6   class     1319 non-null   object
dtypes: object(7)
memory usage: 82.4+ KB
None
Categorical Columns: Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [ ]:
df_encoded = pd.get_dummies(df, columns=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], drop_first=True)
df_encoded.head()

,class,buying_low,buying_med,buying_vhigh,maint_low,maint_med,maint_vhigh,doors_3,doors_4,doors_5more,persons_4,persons_more,lug_boot_med,lug_boot_small,safety_low,safety_med
0,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,True,False
1,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True
2,unacc,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False
3,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
4,unacc,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True

In [ ]:
df_encoded.shape

(1319, 16)

In [ ]:
df_encoded.columns

Index(['class', 'buying_low', 'buying_med', 'buying_vhigh', 'maint_low',
       'maint_med', 'maint_vhigh', 'doors_3', 'doors_4', 'doors_5more',
       'persons_4', 'persons_more', 'lug_boot_med', 'lug_boot_small',
       'safety_low', 'safety_med'],
      dtype='object')

### corr

In [ ]:
df.corr(numeric_only=True)

Empty DataFrame
Columns: []
Index: []